/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005226",
        "on-primary-fixed": "#00210b",
        "tertiary-container": "#b3c8ff",
        "surface-variant": "#353534",
        "primary-fixed-dim": "#00e475",
        "surface-tint": "#00e475",
        "on-primary": "#003918",
        background: "#131313",
        tertiary: "#dce4ff",
        "surface-container": "#201f1f",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#00429b",
        "on-secondary-container": "#562000",
        "secondary-fixed": "#ffdbcb",
        "inverse-on-surface": "#313030",
        "on-tertiary-fixed": "#001945",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        outline: "#859585",
        "on-primary-container": "#00612e",
        "tertiary-fixed": "#d9e2ff",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#fd6c00",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#3b4a3d",
        secondary: "#ffb692",
        "on-secondary": "#562000",
        "primary-container": "#00e676",
        "on-surface-variant": "#bacbb9",
        "on-tertiary-container": "#004eb5",
        "on-background": "#e5e2e1",
        "surface-container-highest": "#353534",
        "primary-fixed": "#62ff96",
        "on-surface": "#e5e2e1",
        surface: "#131313",
        "inverse-primary": "#006d35",
        "on-secondary-fixed": "#341100",
        "on-tertiary": "#002d6e",
        "on-secondary-fixed-variant": "#7a3000",
        "tertiary-fixed-dim": "#b0c6ff",
        "secondary-fixed-dim": "#ffb692",
        primary: "#75ff9e",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        gold: "#FFD700",
        silver: "#C0C0C0",
        bronze: "#CD7F32",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "margin-mobile": "16px",
        xl: "32px",
        lg: "24px",
        sm: "8px",
        gutter: "12px",
        md: "16px",
        base: "4px",
      },
      fontFamily: {
        "label-sm": ["HankenGrotesk_500Medium"],
        "body-md": ["HankenGrotesk_400Regular"],
        "title-md": ["HankenGrotesk_600SemiBold"],
        "display-lg": ["HankenGrotesk_800ExtraBold"],
        "headline-lg": ["HankenGrotesk_700Bold"],
        "stat-value": ["JetBrainsMono_700Bold"],
        "headline-lg-mobile": ["HankenGrotesk_700Bold"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "title-md": ["18px", { lineHeight: "24px" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "40px" }],
        "stat-value": ["20px", { lineHeight: "24px" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px" }],
      },
    },
  },
  plugins: [],
};
